### ISSUE TITLE
Newly created typescript-app project fails compiling / building

### ISSUE THREAD

**Issue by zlatkoc** [projen/projen#3795] opened 2024-08-23 12:02 UTC
Create a new typescript-app project using projen:

```
$ npx projen new typescript-app --default-release-branch master --author-name "X Y" --author-email "xy@email.com"
```

Then try to compile / build it:

```
$ npx projen build
👾 build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 build » compile | tsc --build
../../../../node_modules/@types/katex/index.d.ts:142:46 - error TS2304: Cannot find name 'HTMLElement'.

142 export function render(tex: string, element: HTMLElement, options?: KatexOptions): void;
                                                 ~~~~~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:38:43 - error TS2304: Cannot find name 'Element'.

38 export type HighlightCallback = (element: Element) => void;
                                             ~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:64:46 - error TS2304: Cannot find name 'ParentNode'.

64 export function highlightAllUnder(container: ParentNode, async?: boolean, callback?: HighlightCallback): void;
                                                ~~~~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:89:43 - error TS2304: Cannot find name 'Element'.

89 export function highlightElement(element: Element, async?: boolean, callback?: HighlightCallback): void;
                                             ~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:130:15 - error TS2304: Cannot find name 'Element'.

130     element?: Element | undefined;
                  ~~~~~~~


Found 5 errors.

👾 Task "build » compile" failed when executing "tsc --build"
```

What are these @types dependencies to katex and prismjs doing?

I just want to create a simple command line app using typescript.

**Comment by mrgrain** [comment] 2024-08-23 12:37
> I just want to create a simple command line app using typescript.


This doesn't fix the issue, but for a command line tool, use the `typescript` project. 

`typescript-app` is intended to be a front-end application.

**Comment by zlatkoc** [comment] 2024-08-23 12:44
The same errors persist.

New project with type `typescript`:
```
$ npx projen new typescript --default-release-branch master --author-name "Z Y" --author-email "zy@email.com"
```
Build / compile:
```
npx projen build
👾 build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 build » compile | tsc --build
../../../../node_modules/@types/katex/index.d.ts:142:46 - error TS2304: Cannot find name 'HTMLElement'.

142 export function render(tex: string, element: HTMLElement, options?: KatexOptions): void;
                                                 ~~~~~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:38:43 - error TS2304: Cannot find name 'Element'.

38 export type HighlightCallback = (element: Element) => void;
                                             ~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:64:46 - error TS2304: Cannot find name 'ParentNode'.

64 export function highlightAllUnder(container: ParentNode, async?: boolean, callback?: HighlightCallback): void;
                                                ~~~~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:89:43 - error TS2304: Cannot find name 'Element'.

89 export function highlightElement(element: Element, async?: boolean, callback?: HighlightCallback): void;
                                             ~~~~~~~

../../../../node_modules/@types/prismjs/index.d.ts:130:15 - error TS2304: Cannot find name 'Element'.

130     element?: Element | undefined;
                  ~~~~~~~


Found 5 errors.

👾 Task "build » compile" failed when executing "tsc --build"
```

**Comment by zlatkoc** [comment] 2024-08-23 12:53
Reading the documentation, like for example here `https://projen.io/docs/api/typescript`, nothing points out that the `TypeScriptAppProject` is a front-end application. There is also a `TypeScriptLibraryProject` and `TypeScriptProject`. There are also `ReactProject` and other web project types.

We use extensively `AwsCdkTypeScriptApp` for infrastructure and it works like a charm.

But even if I might have chosen a wrong project type, the newly created / generated project should compile, shouldn't it?

**Comment by zlatkoc** [comment] 2024-08-23 14:08
I have found a temporary solution to the build / compile problem.

After you create new project:
```
$ npx projen new typescript-app --default-release-branch master --author-name "A B" --author-email "ab@email.com"
```

You should amend `.projenrc` like here (note the "`project.tsconfig?.compilerOptions?.lib?.push('dom')`"):
```
import { typescript } from 'projen';
const project = new typescript.TypeScriptAppProject({
  authorEmail: 'ab@email.com',
  authorName: 'A B',
  defaultReleaseBranch: 'master',
  name: 'something',
  projenrcTs: true,

  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});

// add following and compile / build errors will disappear
project.tsconfig?.compilerOptions?.lib?.push('dom');

project.synth();
```

Then you need to regenerate the project:
```
$ npx projen
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
```

Following with:
```
$ npx projen build
👾 build » default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 build » compile | tsc --build
👾 build » test | jest --passWithNoTests --updateSnapshot
 PASS  test/hello.test.ts
  ✓ hello (1 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |
 index.ts |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.797 s
Ran all test suites.
👾 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern  src test build-tools projenrc .projenrc.ts
```

I am not really sure the `typescript-*` projen project types should already include things for web front-ends. That should go to the `web` type of generators.

**Comment by mrgrain** [comment] 2024-08-23 18:07
Oh yes, 100% agree that it should work anyway. Sorry this is also happens for a non app `typescript` project and that the docs aren't up to scratch. I'll need to investigate what's going on here and make sure we're fixing our test infrastructure to catch these issue automatically. 😔

**Comment by mrgrain** [comment] 2024-08-24 18:32
Hi @zlatkoc I cannot reproduce this issue on my end. Neither with `typescript-app` nor with `typescript`.

Looking at the `node_modules/@types` directory, none of the failign types show up:

```
$ ls -go node_modules/@types
total 0
drwxr-xr-x@  7    224B 24 Aug 19:26 babel__core
drwxr-xr-x@  6    192B 24 Aug 19:26 babel__generator
drwxr-xr-x@  7    224B 24 Aug 19:26 babel__template
drwxr-xr-x@  6    192B 24 Aug 19:26 babel__traverse
drwxr-xr-x@  7    224B 24 Aug 19:26 graceful-fs
drwxr-xr-x@  6    192B 24 Aug 19:26 istanbul-lib-coverage
drwxr-xr-x@  6    192B 24 Aug 19:26 istanbul-lib-report
drwxr-xr-x@  6    192B 24 Aug 19:26 istanbul-reports
drwxr-xr-x@  6    192B 24 Aug 19:26 jest
drwxr-xr-x@  6    192B 24 Aug 19:26 json5
drwxr-xr-x@ 57    1.8K 24 Aug 19:26 node
drwxr-xr-x@  6    192B 24 Aug 19:26 stack-utils
drwxr-xr-x@ 10    320B 24 Aug 19:26 yargs
drwxr-xr-x@  6    192B 24 Aug 19:26 yargs-parser
```

---

Looking a bit closer at the path of the errors you are encountering, I can see that the issue is with types that are installed a number (4) directories further upwards in the tree.

```
../../../../node_modules/@types/katex/index.d.ts:142:46
```

This seems to indicate to me that the issue is with your local configuration. Can you try this again in a folder where you don't have modules further up in the filesystem?

This is relatively standard node/typescript behavior. There might be a setting to prevent that, but I'm not convinced it should be the default.

**Comment by mrgrain** [comment] 2024-08-26 12:05
Closing this as a non issue for now. Please let me know if you cannot solve this with my recommendations.

**Closed by mrgrain** 2024-08-26 12:05 UTC
Labels: cannot-reproduce
