### ISSUE TITLE
Release version update not happening properly. 

### ISSUE THREAD

**Issue by nithinM** [projen/projen#1551] opened 2022-01-22 19:11 UTC
I set up the first projen project using the latest (`0.51.10`). When I run the `npx projen bump`, I'm getting 

```
👾 Update /<PATH>/package.json to latest resolved version: 0.0.0
👾 Tags listed on current commit: 
✖ skip version bump on first release
```
I noticed projen project setup does not contain the `.versionrc.json`.

I tried with the older (`0.17.83`) version it gave me the correct output when I executed the `npx projen bump` 

```
➜  projen-2 git:(master) npx projen bump                    
🤖 bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
🤖 bump | git -c "versionsort.suffix=-" tag --sort="-version:refname" --list "v*" | head -n1 > .version.tmp.json
🤖 bump | if [ "$(cat .version.tmp.json)" = "" ]; then echo "v0.1.0" > .version.tmp.json; fi
🤖 bump | standard-version
✔ bumping version in package.json from 0.0.0 to 0.1.1
✔ created .changelog.tmp.md
```

I'm not sure if I need to do additional config to enable version support or a bug in the latest release. Please let me know how can I sort out this issue.

Thanks!

**Comment by mrgrain** [comment] 2022-11-02 13:03
Cannot reproduce with current version. Closing. Please let me know if this still an issue or create a new ticket.

**Closed by mrgrain** 2022-11-02 13:03 UTC
