### ISSUE TITLE
Eslint & prettier configs are conflicting

### ISSUE THREAD

**Issue by Glyphack** [projen/projen#2238] opened 2022-11-13 11:32 UTC
After creating an aws CDK construct library project, if you have prettier formatting enabled(I have it in my IDE) then it conflicts with the default eslint config.
I tried adding these configurations to my .projenrc
```
  prettier: true,
  prettierOptions: { settings: { singleQuote: true, trailingComma: 'es5' } },
```

The issue is that some rules conflict with the default prettier config, like single quotes and trialing commas settings. This can be improved if we add these conflicting configurations to prettier by default. 
Only setting `prettier: true` is not enough and the user has to manually look up the configuration and add these settings. We can either change default prettier config to be compliant with elslint or make the eslint config compliant with the other one.

**Comment by pflorek** [comment] 2022-11-21 00:30
I'm using [editorconfig](https://editorconfig.org/), which is recognized by IDE and prettier. Sometimes I'm also setting line endings in .gitattributes

```typescript
new IniFile(project, ".editorconfig", {
  obj: {
    ["root"]: true,
    ["*"]: {
      ["end_of_line"]: "lf",
      ["charset"]: "utf-8",
    },
    ["*.{js,ts}"]: {
      ["indent_style"]: "space",
      ["indent_size"]: 2,
      ["max_line_length"]: 120,
    },
  },
  marker: true,
});
```

If it's useful I would drop a PR

**Comment by mrgrain** [comment] 2023-03-21 20:17
@Glyphack I can't reproduce this. In my project when I set `prettier: true`, then the `eslint` config correctly adapts to use prettier's settings. Given the default prettier and eslint styles are different, but a run of `projen eslint` fixes that.

Can you confirm the code your using?

**Comment by michael-lowe-nz** [comment] 2023-05-05 06:56
I remember this happening a while ago.
Particularly the conflicting rules on single quotes vs. double quotes.
I couldn't quite figure out how to get the configuration to customise Prettier, so ended up turning off ESlint. I've gone back and tried again, but this issue now appears not to be present. Maybe something has changed somewhere else in projen, Prettier or Beautify 🤷

**Comment by mrgrain** [comment] 2023-05-05 08:10
Thanks for the confirmation. Absolutely possible something else has fixed that.

Closing for now.

**Closed** 2023-05-05 08:15 UTC
Labels: enhancement, needs-investigation
