### ISSUE TITLE
gitlab build workflow

### ISSUE THREAD

**Issue by jlosito** [projen/projen#3532] opened 2024-04-18 17:36 UTC
I use the GitHub build workflow that is generated by projen, but I find myself having to use GitLab often for projects. I would be useful if the same sort of logic could be ported over to its GitLab equivalence and have a toggle like the GitHub build workflow currently has.

**Comment by mrgrain** [comment] 2024-04-19 09:31
Duplicate of https://github.com/projen/projen/issues/2438

**Closed by mrgrain** 2024-04-19 09:31 UTC
