### ISSUE TITLE
bug: npx projen new cdktf-construct doesn't work

### ISSUE THREAD

**Issue by pflorek** [projen/projen#1269] opened 2021-11-30 13:34 UTC
While issuing `npx projen new cdktf-construct` projen gives me following answer:

```shell
Need to install the following packages:
  projen
Ok to proceed? (y) y
projen new [PROJECT-TYPE] [OPTIONS]

Creates a new projen project

Kommandos:
  projen new awscdk-app-ts     AWS CDK app in TypeScript.
  projen new awscdk-construct  AWS CDK construct library project.
  projen new cdk8s-construct   CDK8s construct library project.
  projen new java              Java project.
  projen new jsii              Multi-language jsii library project.
  projen new nextjs            Next.js project without TypeScript.
  projen new nextjs-ts         Next.js project with TypeScript.
  projen new node              Node.js project.
  projen new project           Base project.
  projen new python            Python project.
  projen new react             React project without TypeScript.
  projen new react-ts          React project with TypeScript.
  projen new typescript        TypeScript project.
  projen new typescript-app    TypeScript app.

Positionals:
  PROJECT-TYPE  optional only when --from is used and there is a single project
                type in the external module    
...                            
```

What is the recommended way creating a new cdktf-construct project?

**Comment by eladb** [comment] 2021-11-30 13:43
Basically it requires creating a new project type similar to one of the existing CDK project types.

*I wouldn't categorize this as a bug given this project type has not yet been implemented.*

**Comment by pflorek** [comment] 2021-11-30 13:45
Thank you!

Just saw https://github.com/projen/projen/blob/main/src/cdktf-construct.ts and thought it's ready to go.

**Comment by eladb** [comment] 2021-11-30 13:46
Wait! What?

**Comment by eladb** [comment] 2021-11-30 14:38
I am unable to reproduce this:

```sh
$ npx projen@latest new cdktf-construct
```

Perhaps you have an old version of projen installed on your machine? Try `npm i -g projen` to refresh it.

Closing for now. Let me know if this works.

**Closed by eladb** 2021-11-30 14:38 UTC

**Comment by pflorek** [comment] 2021-12-03 00:22
@eladb Exactly that was the bug. Now with the latest version it works like a charm. Thank you for the hint!

How much effort would it be to always show the current version on the cli like `projen --version` and where to read from. I've seen yargs is used...

**Comment by pflorek** [comment] 2021-12-03 03:17
Found it `npx projen --version` 😄
