### ISSUE TITLE
Switching `jest: true` -> `false` does not remove jest.config.js

### ISSUE THREAD

**Issue by rix0rrr** [projen/projen#2404] opened 2023-01-31 10:21 UTC
This file is fully managed by projen, so it can be removed after I decide I don't need jest support anymore.

**Comment by fynnfluegge** [comment] 2023-02-26 17:24
@rix0rrr how did you detect this bug? I tested several `.projenrc.js` configurations and in all cases the `jest.config.ts` gets deleted.

When synth with

```
const project = new typescript.TypeScriptProject({
  defaultReleaseBranch: 'main',
  name: 'projen-test',
  jest: true,
  jestOptions: {
    testEnvironment: 'node',
    automock: false,
    configFilePath: 'jest.config.js',
  },
});
```

and afterwards setting `jest: false` but keep `jestOptions` and synth again the file gets deleted. Even when `configFilePath` differs from `jest.config.ts` it gets deleted.

**Comment by mrgrain** [comment] 2023-03-09 16:22
Can't reproduce this either. Closing for now.

**Closed by mrgrain** 2023-03-09 16:22 UTC
Labels: bug, needs-investigation
