### ISSUE TITLE
Define `ts-jest` config under `globals` is deprecated.

### ISSUE THREAD

**Issue by drernie** [projen/projen#3130] opened 2023-11-18 19:48 UTC
When running a brand-new projen project, I get:
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
I assume this is in some non-editable file, probably `package.json`:
```
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.dev.json"
      }
    }

```
Is there a fix/workaround, or do I need to wait for projen to release an update?

**Comment by tinovyatkin** [comment] 2023-11-18 20:41
It's just a warning so you may ignore it. If you want to fix it then it can be done like [this](https://github.com/aws/constructs/pull/1957/files#diff-bda22a3de7550efc76dd29e2a427a8d5abd5863f6e96a339ff47390d9bed7d14).

**Comment by mrgrain** [comment] 2023-11-19 12:07
Duplicate of #2361

And what @tinovyatkin said.

**Closed** 2023-11-19 12:07 UTC
