### ISSUE TITLE
`Unsupported option name ("--check-files")` when using Yarn 4

### ISSUE THREAD

**Issue by garysassano** [projen/projen#3114] opened 2023-11-14 05:02 UTC
I got the same issue described in #2285.

I had to switch to Yarn's classic version using `yarn set version classic` to fix the build.

**Comment by mrgrain** [comment] 2023-11-14 09:58
Hi @garysassano you will need to set the `packageManager` to `NodePackageManager.YARN_BERRY` to get the correct behavior. This command has been fixed since #2426 landed.

**Comment by garysassano** [comment] 2023-11-14 10:37
The error is from running `yarn install` on projen's repo, not from setting up my own project.

**Comment by mrgrain** [comment] 2023-11-14 11:27
Gotcha. That works as intended then, the `projen` repo needs yarn classic to be build.

**Closed by mrgrain** 2023-11-14 11:27 UTC
