### ISSUE TITLE
Feature Request: configurable pre-commit git command

### ISSUE THREAD

**Issue by ericxinzhang** [projen/projen#2173] opened 2022-10-14 03:03 UTC
My organisation is using `git defender` which enforces me to run `git defender --setup` command before the first commit for each new repository therefore I am facing the following error:

```
> aws-cdk-ts-app@0.0.0 eslint /Users/me/Projects/aws-cdk-ts-app
> npx projen eslint

Initialized empty Git repository in /Users/me/Projects/aws-cdk-ts-app/.git/
Error: Command failed: git commit --allow-empty -m "chore: project created with projen"
Code Defender: Repository has not been setup with git defender
Run git defender --setup to fix
```

I can't put the command into a precommit hook otherwise it asks / verifies the configuration each time when I commit. 

I checked [source codes](https://github.com/projen/projen/blob/main/src/cli/cmds/new.ts#L324-L332) and don't think projen currently support this feature thus request it

**Comment by mrgrain** [comment] 2022-10-14 08:41
You could pass `--no-git` when creating the new project and then manually run `git defender --setup` and commit projen files.

**Comment by ericxinzhang** [comment] 2022-10-15 22:46
> You could pass `--no-git` when creating the new project and then manually run `git defender --setup` and commit projen files.

Thanks Momo. Yes I had read the doc, source code and knew that, just think turning off the git is a work-around but not a solution so requested the feature if it makes sense.

**Comment by mrgrain** [comment] 2022-11-02 12:23
Duplicate of #1812

**Closed by mrgrain** 2022-11-02 12:23 UTC
Labels: enhancement
