### ISSUE TITLE
Manual releases are broken in new tag-based bumps

### ISSUE THREAD

**Issue by smacintyre** [projen/projen#726] opened 2021-04-23 08:53 UTC
The readme states:

> Bump & release scripts with CHANGELOG generation based on Conventional Commits

This should be updated since the CHANGELOG is no longer generated and release is no longer supported. As per  #634 

Also please document how to use the new bump versioning. It doesn't work out of the box as the old release pattern did -- at least for me. How can we use it?

**Comment by eladb** [comment] 2021-04-23 11:13
@smacintyre See https://github.com/projen/projen/issues/724 for details on bootstrapping

**Comment by smacintyre** [comment] 2021-04-23 12:04
@eladb I'm not sure if that applies. I'm talking about an existing project where we have been using the previous `release` task. So there are existing tags. 

Here is my output:
```bash
$ yarn bump
yarn run v1.22.10
$ npx projen bump
🤖 bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
🤖 bump | git describe --tags --match="v*" --first-parent --abbrev=0 > .version.tmp.json
🤖 bump | standard-version
✔ bumping version in package.json from 0.0.0 to 0.9.6
✔ created .changelog.tmp.md
✔ outputting changes to .changelog.tmp.md
```

The only change is to `package.json` according to git:
```bash
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a")
```

This gets wiped out if I run `yarn projen`. No new tags are created; there is nothing to push.

```bash
$ git push --follow-tags origin main
Everything up-to-date
```

I'm sorry, I'm I completely missing something? How is this new versioning process supposed to work?

**Comment by eladb** [comment] 2021-04-23 12:06
Are you performing manual bumps/releases. In the new model Bumps only happen during release builds (in a GitHub workflow).

The checked in package.json file always says 0.0.0

Of course we need to document!

**Comment by smacintyre** [comment] 2021-04-23 12:06
@eladb Yes, doing manual releases

**Comment by eladb** [comment] 2021-04-23 12:07
Okay so I think the new scheme doesn't support manual releases (and it should). 

Let's repurpose this issue for that

**Comment by smacintyre** [comment] 2021-04-23 12:08
We generally do a bump at the end of a sprint. We don't use Github's release. We use CDK Pipelines for releases
.

**Comment by gradybarrett** [comment] 2021-05-15 01:44
@eladb what do you think about enabling standard-version tagging (and possibly the changelog) if the Github release workflow is disabled?

**Comment by hoegertn** [comment] 2021-05-15 14:52
I think it should be configured separately. We are releasing now tag-based but with Gitlab so we disabled GitHub too.

**Comment by gradybarrett** [comment] 2021-05-15 18:00
I don't have a ton of Gitlab experience but I know they also have the concept of releases which takes care of tagging, artifacts, etc. Wouldn't it make sense for that to be it's own release config? 

But when no product-specific release is configured folks are essentially left with an incomplete-feeling experience. I think at the very least either bump is removed - not ideal - or behaves in a way that's expected. Wouldn't default standard-version behavior be a good place to start?

**Comment by a13zen** [comment] 2021-06-17 21:40
+1 on this, we've been relying on manual releases and loved the changelog + automated git tagging feature based on standard-version from running `npm run release`.  We don't use Github as source control.

**Comment by dan-lind** [comment] 2021-06-30 13:18
The docs remain unchange and still say
`Bump & release scripts with CHANGELOG generation based on Conventional Commits`

_Pretty please_ update the docs to correctly describe how bumping works. 
I've been banging my head against the wall for 4 hours trying to understand why my CHANGELOG is not updated. I now found this issue letting me know that what I'm trying to achieve is in fact no longer supported.

**Comment by eladb** [comment] 2021-06-30 13:21
@dan-lind apologies about that. Will add a comment in the docs that this is currently not supported and hopefully get some time to work on this in the coming days.

**Comment by a13zen** [comment] 2021-06-30 13:35
Until there is a cleaner way around this, I've added the following mega hacky fix:

.projenrc
```
project.buildTask.exec('node ./scripts/fix-version.js pkg-from-version');
```

scripts/fix-version.js
```
// Helper script used to fix package.json version resetting on builds, and helping bump version.json after releases
var fs = require('fs')
var path = require('path')

version_file_path = path.join(__dirname, '..', 'version.json');
package_file_path = path.join(__dirname, '..', 'package.json')

var version_json = require(version_file_path);
var package_json = require(package_file_path); 

var fixType = process.argv[2];
if (!fixType) {
    throw new Error('Please specify a fix type of either ["pkg-from-version"] or ["version-from-pkg"]');
}

if (fixType == "pkg-from-version") {
    package_json.version = version_json.version;
    console.log(package_json.version )
    fs.writeFileSync(package_file_path, JSON.stringify(package_json, null, 2));
} else if (fixType == "version-from-pkg") {
    version_json.version = package_json.version;
    fs.writeFileSync(version_file_path, JSON.stringify(version_json, null, 2));
}
```

Re-added the version.json to keep track of the ever resetting version
```
{
  "version": "0.8.10"
}
```

Finally added a release script
release.sh
```
npm run build
node ./scripts/fix-version.js pkg-from-version
git add -A 
git commit -m 'chore: add rebuilt lib files' || true
node ./node_modules/.bin/standard-version
git push --follow-tags origin master
node ./scripts/fix-version.js version-from-pkg
git add version.json
git commit -m "chore: update version.json"
git push
```

Running standard-version gives back the beloved changelog <3. Note we include the built libs since we don't use a package manager for our lib but deploy directly from source control (which isn't github).

**Comment by eladb** [comment] 2021-07-11 14:30
OK, I made some progress with this. 

You should now be able to run `projen release` (or `yarn release`) and the result will be a `dist/` directory that includes your package artifacts (in whatever language/s you build) and two files: `version.txt` and `changelog.md`. The latest version is resolved (and bumped) from the latest git tag in the local repository. If there are multiple release branches configured, you'll have `projen release:xxx` where `xxx` is the branch name.

You can then run `projen publish:xxx` (where `xxx` can be `npm`, `pypi`, `nuget`, etc) to publish these artifacts from `dist/` to the relevant package manager (requires secrets in environment variables - see error messages for details). Currently, the portion that creates a GitHub Release (and creates the git tag implicitly) is baked into the release GitHub workflow. I think it makes sense that GitHub Releases will be modeled just like any other publishing target (`projen publish:github`).

The missing piece for manual releases is to merge `dist/changelog.md` into the root `CHANGELOG.md` and create and push a git tag based on `dist/version.txt`.

I think the `release` task can also create a local git tag. This can't hurt (famous last words) but really it should be fine even though in the automated release mode the tag is created when the GitHub release is created. The remaining portion is to modify the root CHANGELOG and commit and push the changes.

So let's say `release` will always create the tag and we can introduce an option that will update the `CHANGELOG.md` as part of `release`.

The rest is to `git push --follow-tags origin main` and this can either be left to the user or we can introduce another option that will do that as part of `release` as well.

An alternative approach can be to introduce something like `publish:git` which will (1) create a commit that updates CHANGELOG and; (2) pushes the commit with tags to `origin`.

I am leaning towards the second alternative. The resulting UX will be:

```shell
$ projen release
$ projen publish:git
```

And if users wish to spawn the latter task they can do:

```ts
project.releaseTask.spawn(project.tryFindTask('publish:git'));
```

@smacintyre @a13zen and others, curious what you all think.

**Comment by pgollucci** [comment] 2021-07-11 15:49
LGTM

**Comment by gradybarrett** [comment] 2021-07-11 21:03
> $ projen release
> $ projen publish:git

+1 to this UX.

**Comment by gradybarrett** [comment] 2021-09-10 01:46
Keep

**Comment by dan-lind** [comment] 2021-09-10 10:43
I wanted to check something, not sure if the error I'm getting is a result of me doing something wrong, or the manual release being a bit broken still. 

Whenever I do changes in my library, after adding/commiting everything and doing `yarn release`, this happens:
```
diff --git a/package.json b/package.json
index 1bf4401..e62d65d 100644
--- a/package.json
+++ b/package.json
@@ -90,7 +90,7 @@
   ],
   "main": "lib/index.js",
   "license": "Apache-2.0",
-  "version": "0.0.29",
+  "version": "0.0.0",
   "jest": {
     "testMatch": [
       "**/__tests__/**/*.ts?(x)",
🤖 Task "release" failed when executing "git diff --ignore-space-at-eol --exit-code" (cwd: /home/dxxjmb/git/cdk-constructs)
error Command failed with exit code 1.
```
`git status` shows that indeed the package.json changed. 
I now do another git add/commit, and rerun `yarn release`. This time everything works fine. 

Is there something I can do between my `git commit` and `yarn release` to avoid getting this error?

**Comment by gradybarrett** [comment] 2021-09-10 21:51
@dan-lind this is the antitamper command running. You can disable antitamper to get around that if you're doing fully manual releases.

@Chriscbr can you think of any reason that disabling anti-tamper for manual releases would be undesirable?

**Comment by dan-lind** [comment] 2021-10-01 11:29
@gradybarrett Turns out that the issue was caused by me using `yarn publish` rather than `yarn publish:npm`. 
`yarn publish` updated the version in package.json which subsequently made `yarn release` sad. 
I'm using `yarn publish:npm` now which doesn't touch the version in package.json. On the other hand I also don't get any tags created now, which `yarn publish` did for me. 

Currently my manual release cycle is
```
$ yarn release
$ git tag v$(cat dist/version.txt)
$ yarn publish:npm
```

**Closed** 2021-10-04 17:31 UTC

**Comment by Jithu17** [comment] 2022-04-04 07:41
Hi,

I am doing a manual release through CICD.
I am getting an error as ``Supplied version x.x.x was not found in input changelog. You may want to check it's content.``
Even though the input changelog in dist folder has the version that is required.

```
const inputChangelogContent = await readFile(inputChangelog, "utf-8");
  const changelogVersionSearchPattern = `[${version}]`;

  if (!inputChangelogContent.includes(changelogVersionSearchPattern)) {
    throw new Error(
      `Supplied version ${version} was not found in input changelog. You may want to check it's content.`
    );
  }
```

Should the changelogVersionSearchPattern = `${version}` rather than `[${version}]`
Apologies if I am missing something
